server:
  port: 8060

spring:
  datasource:
     url: jdbc:mysql://localhost:3306/myproject?useUnicode=true&characterEncoding=utf8
     username: root
     password: yhren
     driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql